### ISSUE TITLE
cert.txt not found

### ISSUE THREAD

**Issue by mwenechac** [ErxrilOwl/angular-printer-service#1]
I am trying to implement this but I am getting error 404 on cert.txt file in the service file. 
Any idea how I can fix this?

**Comment by ErxrilOwl** [comment]
Hello sorry for the late reply. This is an old project that I tried to implement so I don't remember much about this. But have you tried generating your own certificate and put in on the cert.txt?

**Comment by mwenechac** [comment]
I managed to fix it.
